version: '2'
services:
    shaktius-app:
        image: shaktius
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shaktius-postgresql:5432/shaktius
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shaktius-postgresql:
        extends:
            file: postgresql.yml
            service: shaktius-postgresql
